### ISSUE TITLE
AWS – "S3 Secure Transport Enabled" False Failures

### ISSUE THREAD

**Issue by chrisoverzero** [aquasecurity/cloudsploit#579]
In the test for "S3 Secure Transport Enabled", Aqua scans to ensure that a condition:

```yaml
Bool:
  aws:SecureTransport: <true|false> # based on whether the Effect is Allow or Deny
```

…is attached to each statement within an S3 Bucket Policy. This is not the only way to achieve this goal. An explicit `Deny` statement can also be applied:

```yaml
Action: s3:*
Effect: Deny
Principal: '*'
Resource:
- !GetAtt Bucket.Arn
- !Sub ${Bucket.Arn}/*
Condition:
  Bool:
    aws:SecureTransport: false
```

This configuration has been checked in the IAM Policy Simulator and comports with [advice from AWS Premium Support][awsps]. The scan should check for a `Deny` statement of this kind and, if present, emit a `PASS` for that bucket without checking each statement of the policy. (If it's not present, do the other thing, natch.)

[awsps]: https://aws.amazon.com/premiumsupport/knowledge-center/s3-bucket-policy-for-config-rule/
